apiVersion: v1
kind: Namespace
metadata:
  name: example
---
apiVersion: v1
kind: Namespace
metadata:
  name: minio
---
apiVersion: v1
data:
  postgresql-password: cG9zdGdyZXMxMjM0NSANCg==
kind: Secret
metadata:
  name: postgres-credentials
  namespace: aiss
---
apiVersion: v1
data:
  postgresql-password: cG9zdGdyZXMgDQo=
kind: Secret
metadata:
  creationTimestamp: null
  name: postgres-credentials
  namespace: example
---
apiVersion: v1
data:
  root-password: bWluaW8xMjM0NQ==
  root-user: bWluaW8=
kind: Secret
metadata:
  name: minio-credentials
  namespace: minio
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: aiss
spec:
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 10.5.0
  install:
    remediation:
      retries: 3
  interval: 20m
  releaseName: postgres
  timeout: 30m
  values:
    existingSecret: postgres-credentials
    fullnameOverride: postgres
    postgresqlDatabase: postgres
    postgresqlUsername: postgres
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: example
spec:
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 1.21.5
  interval: 20m
  releaseName: nginx
  timeout: 30m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: example
spec:
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 10.5.0
  install:
    remediation:
      retries: 3
  interval: 20m
  releaseName: postgres
  timeout: 30m
  values:
    existingSecret: postgres-credentials
    fullnameOverride: postgres
    postgresqlDatabase: postgres
    postgresqlUsername: postgres
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 9.0.6
  interval: 20m
  releaseName: minio
  timeout: 30m
  values:
    auth:
      existingSecret: minio-credentials
