apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: example
spec:
  releaseName: postgres
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 10.5.0
  install:
    remediation:
      retries: 3
  interval: 20m
  timeout: 30m
  values:
    fullnameOverride: postgres
    postgresqlDatabase: postgres
    postgresqlUsername: postgres
    existingSecret: postgres-credentials
