apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  releaseName: minio
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 9.0.6
  interval: 20m
  timeout: 30m
  values:
    auth:
      existingSecret: minio-credentials
